services:
  identity:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8081:8091"
    volumes:
      - .:/identity
      - ~/.m2:/root/.m2  # Cache Maven dependencies
    environment:
      SPRING_PROFILES_ACTIVE: dev